version: '3.8'

services:
  frontend:
    build: ../
    volumes:
      - build_value:/app/build/
    env_file:
      - ../.env
    networks:
      - network

  nginx:
    image: nginx:1.24.0-alpine
    depends_on:
      - frontend
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - build_value:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../logs/:/var/log/nginx/
    networks:
      - network

volumes:
  build_value:

networks:
  network:
    name: mixskins_frontend
